version: "3"
networks:
  nocobase:
    driver: bridge
services:
  nocobase:
    image: node:16-stretch-slim
    networks:
      - nocobase
    command: [ "yarn", "start" ]
    working_dir: /app
    env_file: ./.env
    volumes:
      - ./:/app
    expose:
      - ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
  postgres:
    image: postgres:10
    restart: always
    command: postgres -c wal_level=logical
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - nocobase
